project_id = "aoedhzmdhibangbksywh"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-contact-confirmation]
verify_jwt = false

[functions.send-getstarted-confirmation]
verify_jwt = false
