import { motion } from "framer-motion";
import { ArrowLeft, FileText, AlertTriangle, Scale, CreditCard, Ban, RefreshCw, Mail, Phone } from "lucide-react";
import { useNavigate, Link } from "react-router-dom";

const SKOOL_BLUE = "#4B5FD1";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <motion.header
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="sticky top-0 z-40 bg-white/80 backdrop-blur-md border-b border-gray-100"
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-medium">Back</span>
          </button>
          <h1 className="text-lg font-bold text-gray-900">Terms & Conditions</h1>
          <div className="w-16" />
        </div>
      </motion.header>

      {/* Hero Section */}
      <section className="py-12 md:py-16 px-4 text-center border-b border-gray-100">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div 
            className="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6"
            style={{ backgroundColor: `${SKOOL_BLUE}15` }}
          >
            <FileText className="w-10 h-10" style={{ color: SKOOL_BLUE }} />
          </div>
          <h2 
            className="text-4xl sm:text-5xl font-bold mb-4"
            style={{ color: SKOOL_BLUE }}
          >
            Terms & Conditions
          </h2>
          <p className="text-gray-500">
            Last updated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </motion.div>
      </section>

      {/* Content */}
      <section className="py-12 px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="max-w-4xl mx-auto prose prose-gray prose-lg"
        >
          {/* Introduction */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Scale className="w-6 h-6" style={{ color: SKOOL_BLUE }} />
              Introduction
            </h3>
            <p className="text-gray-600 leading-relaxed">
              Welcome to Business Bots UK. These Terms and Conditions ("Terms") govern your use of our website, AI employee services, and all related products and services offered by Business Bots UK ("we", "our", or "us").
            </p>
            <p className="text-gray-600 leading-relaxed mt-4">
              By accessing our website or using our services, you agree to be bound by these Terms. If you do not agree with any part of these Terms, you must not use our services.
            </p>
          </div>

          {/* Definitions */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Definitions</h3>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li><strong>"AI Employees"</strong> refers to our automated AI agents: Sprout, Nano, Lilly, Like, Skoot, Tobby, Banjo, and Zen</li>
              <li><strong>"Services"</strong> refers to all AI automation services provided by Business Bots UK</li>
              <li><strong>"Client"</strong> or <strong>"you"</strong> refers to any individual or business using our Services</li>
              <li><strong>"Subscription"</strong> refers to any recurring payment plan for our Services</li>
              <li><strong>"Content"</strong> refers to any data, text, or materials provided to or generated by our AI Employees</li>
            </ul>
          </div>

          {/* Services Description */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Our Services</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              Business Bots UK provides AI-powered automation services designed to enhance business operations. Our AI Employees include:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li><strong>Sprout:</strong> Customer service and support automation</li>
              <li><strong>Nano:</strong> Lead generation and qualification</li>
              <li><strong>Lilly:</strong> Appointment scheduling and calendar management</li>
              <li><strong>Like:</strong> Social media engagement and management</li>
              <li><strong>Skoot:</strong> Email marketing and automation</li>
              <li><strong>Tobby:</strong> Data entry and administrative tasks</li>
              <li><strong>Banjo:</strong> Sales support and CRM integration</li>
              <li><strong>Zen:</strong> Analytics and reporting automation</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              Service availability and features may vary based on your subscription plan.
            </p>
          </div>

          {/* Account and Registration */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Account Registration</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              To use our Services, you may need to create an account. You agree to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Provide accurate, current, and complete information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Accept responsibility for all activities under your account</li>
              <li>Notify us immediately of any unauthorised access</li>
              <li>Not share your account with third parties without our consent</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              We reserve the right to suspend or terminate accounts that violate these Terms.
            </p>
          </div>

          {/* Pricing and Payment */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <CreditCard className="w-6 h-6" style={{ color: SKOOL_BLUE }} />
              Pricing and Payment
            </h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our Services are offered at various price points:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li><strong>Single AI Employee:</strong> £297/month per agent</li>
              <li><strong>Team Package:</strong> Multiple agents at discounted rates</li>
              <li><strong>Enterprise:</strong> Custom pricing for large-scale deployments</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              Payment terms:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>All prices are in GBP unless otherwise stated</li>
              <li>VAT will be added where applicable</li>
              <li>Subscriptions are billed monthly in advance</li>
              <li>Payment is due upon invoice</li>
              <li>We accept major credit cards and bank transfers</li>
            </ul>
          </div>

          {/* Subscription Billing via Stripe */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Subscription Billing</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              Paid subscriptions (including Autopilot SEO at £199/month) are processed securely via Stripe. By subscribing, you agree to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Recurring monthly charges to your provided payment method</li>
              <li>Stripe's <a href="https://stripe.com/legal" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: SKOOL_BLUE }}>Terms of Service</a> and <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: SKOOL_BLUE }}>Privacy Policy</a></li>
              <li>Automatic renewal unless cancelled before the next billing date</li>
              <li>Price changes communicated at least 30 days in advance</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              We do not store your full credit card details. All payment information is handled directly by Stripe's PCI-compliant infrastructure.
            </p>
          </div>

          {/* Limitation of Liability for AI-Generated Content */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">AI-Generated Content Disclaimer</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              Our Autopilot SEO and blog engine services use artificial intelligence to generate content. You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>AI-generated content is produced algorithmically and may contain inaccuracies, errors, or outdated information</li>
              <li>You are solely responsible for reviewing, approving, and publishing any AI-generated content to your own channels (including Facebook Pages and Google Business Profiles)</li>
              <li>We are not liable for any consequences arising from AI-generated content published to your accounts, including but not limited to reputational damage, regulatory penalties, or loss of business</li>
              <li>Content auto-published via connected OAuth accounts is done at your explicit instruction and enablement</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              We recommend reviewing auto-published content regularly to ensure it meets your brand standards and compliance requirements.
            </p>
          </div>

          {/* Cancellation and Refunds */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <RefreshCw className="w-6 h-6" style={{ color: SKOOL_BLUE }} />
              Cancellation and Refunds
            </h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              <strong>Cancellation Policy:</strong>
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>You may cancel your subscription at any time</li>
              <li>Cancellation takes effect at the end of the current billing period</li>
              <li>No refunds for partial months of service</li>
              <li>Cancellation requests must be submitted in writing</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              <strong>Refund Policy:</strong>
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>14-day cooling-off period for new subscriptions</li>
              <li>Refunds processed within 14 business days</li>
              <li>No refunds after the cooling-off period</li>
              <li>Setup fees are non-refundable</li>
            </ul>
          </div>

          {/* Acceptable Use */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <Ban className="w-6 h-6" style={{ color: SKOOL_BLUE }} />
              Acceptable Use Policy
            </h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              You agree not to use our Services to:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Violate any laws or regulations</li>
              <li>Infringe intellectual property rights</li>
              <li>Send spam or unsolicited communications</li>
              <li>Transmit malware or malicious code</li>
              <li>Attempt to gain unauthorised access to our systems</li>
              <li>Harass, abuse, or harm others</li>
              <li>Impersonate any person or entity</li>
              <li>Engage in fraudulent activities</li>
              <li>Collect user data without consent</li>
              <li>Interfere with or disrupt our Services</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              Violation of this policy may result in immediate termination of your account without refund.
            </p>
          </div>

          {/* AI Limitations */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <AlertTriangle className="w-6 h-6" style={{ color: SKOOL_BLUE }} />
              AI Service Limitations
            </h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>AI Employees are automated systems and may occasionally produce errors</li>
              <li>AI-generated content should be reviewed before critical use</li>
              <li>We do not guarantee 100% accuracy of AI responses</li>
              <li>AI Employees cannot replace professional advice (legal, medical, financial)</li>
              <li>Service availability is subject to technical limitations</li>
              <li>Performance may vary based on input quality and complexity</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              We recommend maintaining human oversight for all critical business decisions.
            </p>
          </div>

          {/* Intellectual Property */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Intellectual Property</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              <strong>Our Property:</strong> All intellectual property rights in our Services, including software, algorithms, trademarks, and content, remain our exclusive property.
            </p>
            <p className="text-gray-600 leading-relaxed mb-4">
              <strong>Your Content:</strong> You retain ownership of content you provide to our Services. You grant us a licence to use this content to provide our Services.
            </p>
            <p className="text-gray-600 leading-relaxed">
              <strong>Generated Content:</strong> Content generated by our AI Employees using your data is licensed to you for your business use, subject to these Terms.
            </p>
          </div>

          {/* Limitation of Liability */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Limitation of Liability</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2">
              <li>Our Services are provided "as is" without warranty</li>
              <li>We are not liable for indirect, incidental, or consequential damages</li>
              <li>Our total liability is limited to the amount paid for Services in the preceding 12 months</li>
              <li>We are not responsible for third-party services or integrations</li>
              <li>We are not liable for data loss caused by your actions or third parties</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-4">
              Nothing in these Terms excludes liability for death, personal injury, or fraud caused by our negligence.
            </p>
          </div>

          {/* Indemnification */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Indemnification</h3>
            <p className="text-gray-600 leading-relaxed">
              You agree to indemnify and hold harmless Business Bots UK, its directors, employees, and agents from any claims, damages, losses, or expenses arising from:
            </p>
            <ul className="list-disc pl-6 text-gray-600 space-y-2 mt-3">
              <li>Your use of our Services</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights</li>
              <li>Content you provide to our Services</li>
            </ul>
          </div>

          {/* Governing Law */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Governing Law</h3>
            <p className="text-gray-600 leading-relaxed">
              These Terms are governed by the laws of England and Wales. Any disputes arising from these Terms or your use of our Services shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </div>

          {/* Changes to Terms */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Changes to Terms</h3>
            <p className="text-gray-600 leading-relaxed">
              We reserve the right to modify these Terms at any time. Changes will be effective upon posting to our website. Your continued use of our Services after changes constitutes acceptance of the new Terms. We will notify you of material changes via email or through our Services.
            </p>
          </div>

          {/* Severability */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Severability</h3>
            <p className="text-gray-600 leading-relaxed">
              If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect. The unenforceable provision will be modified to the minimum extent necessary to make it enforceable.
            </p>
          </div>

          {/* Contact Information */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Contact Information</h3>
            <p className="text-gray-600 leading-relaxed mb-4">
              For questions about these Terms, please contact us:
            </p>
            <div className="space-y-3">
              <a 
                href="mailto:ai@businessbotsuk.com"
                className="flex items-center gap-3 text-gray-700 hover:text-gray-900 transition-colors"
              >
                <Mail className="w-5 h-5" style={{ color: SKOOL_BLUE }} />
                ai@businessbotsuk.com
              </a>
              <a 
                href="tel:08006546949"
                className="flex items-center gap-3 text-gray-700 hover:text-gray-900 transition-colors"
              >
                <Phone className="w-5 h-5" style={{ color: SKOOL_BLUE }} />
                0800 654 6949
              </a>
            </div>
            <p className="text-gray-600 leading-relaxed mt-4">
              <strong>Business Bots UK</strong><br />
              United Kingdom
            </p>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-50 py-8 px-4 border-t border-gray-100">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex justify-center gap-6 mb-4">
            <Link to="/privacy" className="text-gray-600 hover:text-gray-900 text-sm">
              Privacy Policy
            </Link>
            <Link to="/contact" className="text-gray-600 hover:text-gray-900 text-sm">
              Contact Us
            </Link>
          </div>
          <p className="text-gray-500 text-sm">
            © {new Date().getFullYear()} Business Bots UK. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Terms;
